name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
    steps:
      - uses: actions/checkout@v2

      # - uses: actions/setup-node@v2
      # with:
      #   node-version: '18'
      # - run: npm install -g pnpm
      # - run: pnpm install
      # - run: pnpm migrate

      - uses: oven-sh/setup-bun@v1
      - name: Run migration
        run: bun run ./src/lib/db/migrate.ts
